name = "lipu"
main = ".svelte-kit/cloudflare/_worker.js"
compatibility_flags = ["nodejs_als"]
compatibility_date = "2026-05-24"

[observability]
enabled = true
logs = { enabled = true, invocation_logs = true }
traces.enabled = true

[assets]
binding = "ASSETS"
directory = ".svelte-kit/cloudflare"

# [[services]]
# binding = "SONA_API"
# service = "sona-api"
# remote = true
